#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export FAULTCHECK_PATH=$DIR"/FaultCheck"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$FAULTCHECK_PATH

export APPLICATION_PATH=$DIR"/Examples/E2E_Scala/Application"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$APPLICATION_PATH

